hmcts/snl-frontend

src/app/problems/components/problems-table/problems-table.component.html
src/app/problems/components/problems-table/problems-table.component.scss
src/app/problems/components/problems-table/problems-table.component.ts

Added `References description` to the table, 
updated scss

Improved problems list

---

src/app/core/callendar/components/callendar.component.ts
src/app/core/callendar/containers/calendar-container.component.ts
src/app/planner/containers/planner.component.ts
src/app/sessions/services/sessions-service.ts

Fix for missing hearings after calendar event click and some related stuff

Bugfix/sl 904/related to this story fixes

---

src/app/hearing-part/components/listing-create/listing-create.component.html
src/app/hearing-part/components/listing-create/listing-create.component.scss
src/app/hearing-part/components/listing-create/listing-create.component.ts

Simplify html,
Added validation
Make it max-width: 400 px
Tided up ts code

Improved adding listing request form:

---

src/app/core/callendar/components/callendar.component.html
src/app/core/callendar/components/callendar.component.ts

The problem was with the calendar initialization. Component tried to make a call on init, but calendar itself hasn't been loaded yet.
I added a handler that fetches data when a calendar is initialized.

Fixed fetching data on calendar initial load

---

src/app/sessions/containers/sessions-search/sessions-search.component.spec.ts

Added missing entry component by overriding BrowserDynamicTestingModule

fixed unit tests - added TransactionDialogComponent by overriding BrowserDynamicTestingModule

---

src/app/app.module.ts
src/app/common/ng-fullcalendar/ng-full-calendar.component.ts
src/app/core/callendar/components/calendar.component.ts
src/app/core/home/home.component.ts
src/app/features/notification/reducers/notification.reducer.ts
src/app/hearing-part/components/listing-create/listing-create.component.ts
src/app/hearing-part/effects/hearing-part.effects.ts
src/app/hearing-part/effects/listing-create.effects.ts
src/app/hearing-part/reducers/hearing-part.reducer.ts
src/app/hearing-part/services/hearing-part-modification-service.ts
src/app/hearing-part/services/hearing-part-service.ts
src/app/problems/containers/problems/problems-page.component.ts
src/app/problems/effects/problem.effects.ts
src/app/problems/reducers/problem.reducer.ts
src/app/rooms/reducers/index.ts
src/app/security/auth-toolbar-element/auth-toolbar-element.component.ts
src/app/security/login/login.component.ts
src/app/sessions/components/session-table/session-table.component.ts
src/app/sessions/components/transaction-dialog/transaction-dialog.component.ts
src/app/sessions/containers/sessions-create/sessions-create.component.ts
src/app/sessions/containers/sessions-page/sessions-page.component.ts
src/app/sessions/containers/sessions-propositions-search/sessions-propositions-search.component.spec.ts
src/app/sessions/containers/sessions-propositions-search/sessions-propositions-search.component.ts
src/app/sessions/containers/sessions-search/sessions-search.component.ts
src/app/sessions/reducers/index.ts
src/app/sessions/reducers/transaction.reducer.ts
src/app/sessions/services/sessions-creation.service.ts
src/app/sessions/services/sessions-service.ts
src/app/sessions/services/sessions-statistics-service.ts
tsconfig.json

- Added unit tests for session-search-component
- Fixed bugs found by them (related with using wrong selectors)
- Removed unused code + enabled flag to lint that

SnL-996 code coverage - units for session search component

---

src/app/core/callendar/components/calendar.component.html
src/app/core/callendar/components/calendar.component.spec.ts
src/app/core/callendar/components/calendar.component.ts
src/app/core/callendar/transformers/icalendar-transformer.ts

Note, two methods were omitted on purpose as there are to be changed by one of the stories (related with performance)

Feature/996 code coverage - unit tests for calendar component

---

src/app/planner/containers/planner.component.spec.ts
src/app/planner/containers/planner.component.ts

Feature/996 code coverage - unit tests for planner component

---

src/app/planner/components/room-planner/room-planner.component.spec.ts

SNL-996 - Added unit tests for room planner component

---

package.json
src/app/features/notification/effects/notification.effects.ts
src/app/hearing-part/components/hearing-parts-preview/hearing-parts-preview.component.html
src/app/hearing-part/components/hearing-parts-preview/hearing-parts-preview.component.ts
src/app/hearing-part/effects/hearing-part.effects.ts
src/app/hearing-part/models/hearing-part-dialog-contents.ts
src/app/hearing-part/models/hearing-part.ts
src/app/hearing-part/models/session-assignment.ts
src/app/hearing-part/services/hearing-part-service.ts
src/app/planner/components/room-planner/room-planner.component.spec.ts
src/app/sessions/components/session-table/session-table.component.ts
src/app/sessions/containers/sessions-search/sessions-search.component.spec.ts
src/app/sessions/containers/sessions-search/sessions-search.component.ts
src/app/sessions/models/session.viewmodel.ts
src/app/sessions/reducers/index.ts
src/app/sessions/services/sessions-statistics-service.spec.ts
yarn.lock

https://tools.hmcts.net/jira/browse/SL-1000
Optimistic db locking for assigning HearingPart to Session.

Feature/sl 1000/db locking

---

Jenkinsfile_CNP
e2e/flows/navigation.flow.ts
e2e/pages/top-menu.po.ts
e2e/specs/session.e2e-spec.ts
src/app/hearing-part/components/listing-create/listing-create.component.html
src/app/hearing-part/components/listing-create/listing-create.component.spec.ts
src/app/hearing-part/components/listing-create/listing-create.component.ts
src/app/hearing-part/models/listing-create.ts
src/app/sessions/containers/sessions-create/sessions-create.component.ts
src/app/sessions/containers/sessions-propositions-search/sessions-propositions-search.component.ts
src/app/sessions/containers/sessions-search/sessions-search.component.ts
src/app/utils/array-utils.spec.ts
src/app/utils/array-utils.ts

Added two new fields to Create new listing request form, updated unit tests

[PREVIEW] SL-1108 added additional attributes to create new listing request form

---

src/app/core/home/home.component.html
src/app/core/home/home.component.scss
src/app/sessions/containers/sessions-search/sessions-search.component.html
src/app/sessions/containers/sessions-search/sessions-search.component.scss
src/styles.css

Fixed moved top bar + make responsible search session screen

Fix UI glitch

---

src/app/sessions/components/sessions-propositions-table/sessions-propositions-table.component.html
src/app/sessions/components/sessions-propositions-table/sessions-propositions-table.component.ts
src/app/sessions/containers/sessions-propositions-search/sessions-propositions-search.component.spec.ts
src/app/sessions/models/session-proposition-view.model.ts
src/app/sessions/reducers/index.ts

SL-1510 fix for dates with moments.js

SL-1510 fix for dates with moments.js

---

e2e/enums/hearing-types.ts
e2e/models/data/listing-creation-form-data.ts
e2e/models/listing-creation-form.ts
e2e/pages/session-search.po.ts
e2e/pages/top-menu.po.ts
e2e/pages/transaction-dialog.po.ts
e2e/specs/amend-listing-request.e2e-spec.ts
e2e/specs/session.e2e-spec.ts
src/app/sessions/components/sessions-create-form/sessions-create-form.component.html
src/styles.css

Adjusted e2e tests
Fix bug related with start time and duration of a session

[PREVIEW] SL-1351 rules changes to make use of session type adjust e2e tests

---

src/app/core/callendar/components/calendar.component.scss
src/app/core/callendar/transformers/default-data-transformer.spec.ts
src/app/core/callendar/transformers/default-data-transformer.ts
src/app/features/notification/components/dialog-with-actions/dialog-with-actions.component.ts
src/app/features/transactions/components/transaction-dialog/transaction-dialog.component.html
src/app/features/transactions/components/transaction-dialog/transaction-dialog.component.scss
src/app/features/transactions/components/transaction-dialog/transaction-dialog.component.ts
src/app/features/transactions/models/transaction-dialog-data.model.ts
src/app/hearing-part/components/hearing-parts-preview/hearing-parts-preview.component.ts
src/app/hearing-part/components/listing-create/listing-create.component.ts
src/app/judges/reducers/index.ts
src/app/planner/containers/planner.component.spec.ts
src/app/planner/containers/planner.component.ts
src/app/planner/planner.module.ts
src/app/planner/services/summary-message.service.spec.ts
src/app/planner/services/summary-message.service.ts
src/app/rooms/reducers/index.ts
src/app/sessions/containers/sessions-create/sessions-create.component.ts
src/app/sessions/containers/sessions-propositions-search/sessions-propositions-search.component.ts
src/app/sessions/containers/sessions-search/sessions-search.component.ts

Added Summary message + its service + unit tests

[PREVIEW] SL-1503 Assign joh or room via planner

---

package.json
server.ts

This is to fix some of the security issues raised by ZAP

added helmetjs configuration

---

e2e/pages/top-menu.po.ts
package.json
server.ts

Reverts hmcts/snl-frontend#203
I'm reverting this due problem with e2e tests :(
@satyachundur please double check this changes with e2e tests (it was causing e2e to fails and master couldn't pass the pipeline 
(your PR was passing previously as it was created without PREVIEW flag)
Please let us know if you have any problems, we will try to help although we've just started the sprint.

[PREVIEW] Revert "added helmetjs configuration"

---

e2e/flows/login.flow.ts
e2e/pages/planner.po.ts
e2e/pages/session-details-dialog.po.ts
e2e/pages/top-menu.po.ts
e2e/pages/transaction-dialog.po.ts
e2e/protractor.conf.js
e2e/specs/amend-listing-request.e2e-spec.ts
e2e/specs/login.e2e-spec.ts
e2e/specs/planner.e2e-spec.ts
e2e/specs/problem-list.e2e-spec.ts
e2e/specs/session-amend-list.e2e-spec.ts
e2e/specs/session.e2e-spec.ts
e2e/utils/element-helper.ts

[PREVIEW] SL-1940 try to fix tests

---

e2e/protractor.conf.js
src/app/hearing-part/components/hearings-filter/hearings-filter.component.ts
src/app/hearing-part/components/listing-create/listing-create.component.ts
src/app/hearing-part/models/communication-facilitators.model.ts
yarn.lock

PR with fixes for Kamil's comments

Feature/sl 1551/cr fixes

---

src/app/hearing/components/view-hearing/view-hearing.component.html

Bugfix to show judge name and fixed multisession flag

[PREVIEW] bugfix/SL-1969/duration-and-session-hearing-details

---

src/app/common/ng-fullcalendar/ng-full-calendar.component.ts
src/app/planner/containers/planner.component.ts
src/app/planner/services/summary-message.service.ts

Workaround for an undefined 'duration' in 'eventResize'

[PREVIEW] Bugfix/sl 1894/planner changing start time

---

Dockerfile
Jenkinsfile_CNP
Jenkinsfile_nightly
Jenkinsfile_parameterized
README.md
docker-compose.yml
e2e/utils/api.ts
kubernetes/config.aat.yaml
kubernetes/config.saat.yaml
kubernetes/deployment.template.yaml

[AKS] SL-1919: enable AKS

---

src/app/hearing-part/components/hearings-table/hearings-table.component.html
src/app/hearing-part/components/hearings-table/hearings-table.component.spec.ts
src/app/hearing-part/components/hearings-table/hearings-table.component.ts
src/app/hearing-part/components/listing-note-list/listing-note-list.component.ts
src/app/notes/components/notes-list-dialog/notes-list-dialog.component.spec.ts
src/app/notes/components/notes-list-dialog/notes-list-dialog.component.ts
src/app/notes/models/note.model.ts
src/app/notes/models/note.viewmodel.ts

[AKS] Bugfix/sl 2062/notes display incosistency

---

src/app/sessions/containers/sessions-listings-search/sessions-listings-search.component.spec.ts
src/app/sessions/containers/sessions-listings-search/sessions-listings-search.component.ts
src/app/utils/moment-utils.spec.ts
src/app/utils/moment-utils.ts
src/app/utils/time-utils.spec.ts
src/public/config.json

[AKS] SL-2170: Fixed logic, unit tests to do

---

docker-compose.yml

Docker config now reference local machine host and ports rather than
specific containers for other components

SL-2217 docker with local processes
